plugins:
- jekyll-remote-theme 

# Theme
# look back to https://github.com/pages-themes/midnight for info on further customizations
remote_theme: pages-themes/midnight@v0.2.0

title: Richard Meredith
tagline: Stuff and things
description: This is where my website's gonna go!
show_downloads: false
